# Generated by Django 5.2.1 on 2025-05-27 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_author_alter_task_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='goal',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.goal'),
            preserve_default=False,
        ),
    ]
