# Generated by Django 5.2.1 on 2025-06-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='execution_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
