# Generated by Django 5.2.1 on 2025-06-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_notificationtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationType',
        ),
    ]
